language: java
jdk:
  - oraclejdk8

before_install:
 - chmod +x gradlew

notifications:
 email: false

deploy:
  on:
    branch: master
  provider: elasticbeanstalk
  access_key_id: $TRAVIS_AWS_ACCESS_KEY
  secret_access_key:
    secure: $TRAVIS_AWS_SECRET_KEY
  region: $TRAVIS_AWS_REGION
  app: $TRAVIS_AWS_APP
  env: $TRAVIS_AWS_ENV
