language: java
jdk:
  - oraclejdk8

before_install:
 - chmod +x gradlew

notifications:
 email: false

deploy:
  on:
    branch: master
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  bucket_name: $AWS_BUCKET_NAME
  region: $AWS_REGION
  app: $AWS_APP
  env: $AWS_ENV

# working example: https://travis-ci.org/ExampleDriven/spring-boot-aws-elasticbeanstalk-example